version: '3'

services:
  jupyter_notebook_reader:
    image: echocool/jupyter_notebook_reader:${VERSION:-latest}
    container_name: jupyter_notebook_reader
    build:
      context: .
    expose:
      - "5000"
    ports:
      - "28909:5000"
    restart: on-failure