name: Docker-compose build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]



jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - run: docker-compose --version
      - name: Build with docker-compose
        run: docker-compose build --parallel
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          username: echocool
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker-compose push
